Repository Schniz/fnm, pull requests merged in 2019-10, with the labels that each got.

#149 Update to v6.17.1 in `partial_semver` feature test
  feature_tests/partial_semver/run.sh
Labels: PR: Internal

#146 Add support for `lts/*`
  executable/Env.re
  executable/Install.re
  executable/ListLocal.re
  executable/Use.re
  feature_tests/latest-lts/.nvmrc
  feature_tests/latest-lts/run.sh
  feature_tests/run.sh
  library/Dotfiles.re
  library/Fs.re
  library/Path.re
  library/Result.re
  library/System.re
  library/VersionListing.re
  library/VersionListingLts.re
  library/Versions.re
  library/dune
  package.json
Labels: PR: New Feature

#151 Add a CI check for code formatting
  .github/workflows/refmt.yml
  fmt.esy.lock/.gitattributes
  fmt.esy.lock/.gitignore
  fmt.esy.lock/index.json
  fmt.esy.lock/opam/base-threads.base/opam
  fmt.esy.lock/opam/base-unix.base/opam
  fmt.esy.lock/opam/conf-m4.1/opam
  fmt.esy.lock/opam/cppo.1.6.6/opam
  fmt.esy.lock/opam/dune.1.11.3/opam
  fmt.esy.lock/opam/menhir.20190924/opam
  fmt.esy.lock/opam/merlin-extend.0.5/opam
  fmt.esy.lock/opam/ocaml-migrate-parsetree.1.4.0/opam
  fmt.esy.lock/opam/ocamlbuild.0.14.0/opam
  fmt.esy.lock/opam/ocamlfind.1.8.1/files/ocaml-stub
  fmt.esy.lock/opam/ocamlfind.1.8.1/files/ocamlfind.install
  fmt.esy.lock/opam/ocamlfind.1.8.1/opam
  fmt.esy.lock/opam/ppx_derivers.1.2.1/opam
  fmt.esy.lock/opam/result.1.4/opam
  fmt.esy.lock/overrides/opam__s__dune_opam__c__1.11.3_opam_override/package.json
  fmt.esy.lock/overrides/opam__s__ocamlbuild_opam__c__0.14.0_opam_override/files/ocamlbuild-0.14.0.patch
  fmt.esy.lock/overrides/opam__s__ocamlbuild_opam__c__0.14.0_opam_override/package.json
  fmt.esy.lock/overrides/opam__s__ocamlfind_opam__c__1.8.1_opam_override/files/findlib-1.8.1.patch
  fmt.esy.lock/overrides/opam__s__ocamlfind_opam__c__1.8.1_opam_override/package.json
  fmt.json
  library/VersionListing.re
  library/VersionListingLts.re
  package.json
Labels: PR: Internal

#153 Add missing `exit 1`s to `partial_semver` tests
  feature_tests/partial_semver/run.sh
Labels: PR: Internal

#148 Make `env` smoke test pass when run with fish
  test/SmokeTest.re
Labels: PR: Internal

#150 Add missing log level to `env` output for Fish shell
  executable/Env.re
Labels: PR: Bugfix

#154 Run all feature tests
  feature_tests/run.sh
Labels: PR: Internal

#158 Uncapitalise "Node" in `--multi` description
  executable/FnmApp.re
Labels: PR: Documentation

#157 Rename `--base-dir` to `--fnm-dir` in README
  README.md
Labels: PR: Documentation
