Repository Schniz/fnm, pull requests merged in 2019-07, with the labels that each got.

#119 Update README.md
  README.md
Labels: PR: Documentation

#118 Add note about upgrading
  README.md
Labels: PR: Documentation

#123 Fix typo in successfully
  docs/fnm.svg
  executable/Install.re
Labels: PR: Documentation

#125 format versions in `uninstall`
  executable/Uninstall.re
  executable/Use.re
  library/Http.re
  library/Versions.re
Labels: PR: Bugfix

#130 Fix issues related to help pages
  executable/FnmApp.re
Labels: PR: Documentation

#133 Fix Windows build once again!
  windows.json
Labels: PR: Internal

#131 Deprecates MacOS installation using the script in favor of Homebrew
  .ci/install.sh
  README.md
Labels: PR: Bugfix
