Repository Schniz/fnm, pull requests merged in 2019-05, with the labels that each got.

#99 fix EACCES error when installing an already downloaded version
  library/Fs.re
Labels: PR: Bugfix

#100 Add Semver to library, an simple non-spec implementation of semver
  esy.lock/index.json
  esy.lock/opam/dune.1.9.3/opam
  esy.lock/opam/ocaml-migrate-parsetree.1.3.0/opam
  esy.lock/opam/ppx_tools_versioned.5.2.1/opam
  esy.lock/opam/ppx_tools_versioned.5.2.2/opam
  esy.lock/opam/semver.0.1.0/opam
  esy.lock/overrides/opam__s__conf_pkg_config_opam__c__1.1_opam_override/package.json
  esy.lock/overrides/opam__s__dune_opam__c__1.9.3_opam_override/package.json
  library/Semver.re
  library/Semver.rei
  library/Versions.re
  library/dune
  package.json
  test/TestFnm.re
  test/TestSemver.re
Labels: PR: Internal

#102 Implement `realpath` instead of binding to C library
  executable/ListInstallations.re
  executable/ListLocal.re
  executable/ListRemote.re
  library/Fs.re
  library/Versions.re
Labels: PR: Internal

#98 Add `uninstall` command
  executable/FnmApp.re
  executable/Uninstall.re
  library/Fs.re
  library/Versions.re
Labels: PR: New Feature

#103 Fix missing aliases due to newer `realpath`
  executable/Use.re
  library/Versions.re
Labels: PR: Bugfix

#104 Add a 'debug' log level
  executable/Alias.re
  executable/FnmApp.re
  executable/Install.re
  executable/Uninstall.re
  executable/Use.re
  feature_tests/existing_installation/run.sh
  library/Config.re
  library/LogLevel.re
  library/Logger.re
  test/__snapshots__/Smoke_test.4d362c3c.0.snapshot
Labels: PR: New Feature
