Repository Schniz/fnm, pull requests merged in 2019-03, with the labels that each got.

#72 Fix alias paths
  executable/Alias.re
  feature_tests/aliases/run.sh
  library/Versions.re
Labels: PR: Bugfix

#68 Infer shells automatically, and `use` versions based on the current working directory (optional)
  .ci/install.sh
  README.md
  executable/Env.re
  executable/FnmApp.re
  feature_tests/fish/run.fish
  feature_tests/use_on_cd/app/.nvmrc
  feature_tests/use_on_cd/run.sh
  library/System.re
Labels: PR: New Feature

#77 Fix "command not found: elsif" error
  executable/Env.re
Labels: PR: Bugfix

#78 Add a test to `use-on-cd` when `.node-version` is found
  feature_tests/use_on_cd/dot_node_version/.node-version
  feature_tests/use_on_cd/nvmrc/.nvmrc
  feature_tests/use_on_cd/run.sh
Labels: PR: Internal

#79 Guard from more non-existent directories errors
  library/Fs.re
  library/Versions.re
Labels: PR: Bugfix

#83 fix: remove unmatched quote written in the fish config file
  .ci/install.sh
Labels: PR: Bugfix

#85 Update README.md
  README.md
Labels: PR: Documentation

#86 Add support for interactive installation for use
  executable/Use.re
  library/Config.re
  library/dune
  package.json
Labels: PR: New Feature
