Repository Schniz/fnm, pull requests merged in 2019-04, with the labels that each got.

#90 Installation script doesn't use GitHub API, but a link to the latest directly
  .ci/install.sh
Labels: PR: Bugfix

#91 Fix `fnm env` for fish shell.
  executable/Env.re
Labels: PR: Bugfix

#95 Shorten installation script url
  README.md
Labels: PR: Documentation

#93 Add support for log level (closes #33)
  README.md
  executable/Alias.re
  executable/Env.re
  executable/FnmApp.re
  executable/Install.re
  executable/Use.re
  feature_tests/log-level-error/run.sh
  feature_tests/log-level-quiet/run.sh
  library/Config.re
  library/LogLevel.re
  library/Logger.re
  library/dune
  package.json
  test/__snapshots__/Smoke_test.4d362c3c.0.snapshot
Labels: PR: New Feature
