Repository Schniz/fnm, pull requests merged in 2019-12, with the labels that each got.

#176 Specify the release to the install script
  .ci/install.sh
Labels: PR: New Feature

#179 Bump lwt version
  esy.lock/index.json
  esy.lock/opam/lwt.5.0.1/opam
  esy.lock/opam/ocplib-endian.1.0/opam
  esy.lock/overrides/opam__s__ocplib_endian_opam__c__1.0_opam_override/files/esy-fix.patch
  esy.lock/overrides/opam__s__ocplib_endian_opam__c__1.0_opam_override/files/ocplib-endian-0.8.patch
  esy.lock/overrides/opam__s__ocplib_endian_opam__c__1.0_opam_override/package.json
  package.json
Labels: PR: Internal

#182 Fix #181 by dropping `exit(1)`
  executable/Alias.re
  executable/Env.re
  executable/FnmApp.re
  executable/Install.re
  executable/ListLocal.re
  executable/ListRemote.re
  executable/Uninstall.re
  executable/Use.re
Labels: PR: Bugfix
