Repository Schniz/fnm, pull requests merged in 2019-09, with the labels that each got.

#132 Fix spelling of availability in install.sh
  .ci/install.sh
Labels: PR: Documentation

#138 Do uninstallation in steps
  library/Fs.re
  test/TestFnm.re
  test/TestFs.re
Labels: PR: Bugfix

#142 Drop buildsInSource
  .ci/create-static-binary.sh
  azure-pipelines.yml
  docs/record_screen.sh
  package.json
  test/TestFramework.re
Labels: PR: Internal
