Repository Schniz/fnm, pull requests merged in 2019-02, with the labels that each got.

#50 Added CHANGELOG
  CHANGELOG.md
  esy.lock/index.json
  esy.lock/overrides/opam__s__core__kernel_opam__c__v0.11.1_opam_override/files/core_kernel-0.11.1.patch
  esy.lock/overrides/opam__s__core__kernel_opam__c__v0.11.1_opam_override/package.json
  package.json
Labels: PR: Documentation

#49 Add a `--fnm-dir` option to `fnm env`
  README.md
  executable/Env.re
  executable/FnmApp.re
  test/__snapshots__/Smoke_test.4d362c3c.0.snapshot
Labels: PR: Documentation

#55 Make tests faster by using cnpmjs as Node.js mirror in tests
  feature_tests/node_mirror_installation/run.sh
Labels: PR: Internal

#54 Infer complete semver (`vX.X.X`) out of partial input (`vX`/`vX.X`).
  executable/Install.re
  executable/Use.re
  feature_tests/partial_semver/run.sh
  library/Versions.re
Labels: PR: New Feature

#56 Correct status code on `install` failures
  executable/Install.re
Labels: PR: Bugfix

#48 Parameterize the install script for relative install of fnm
  .ci/install.sh
  README.md
Labels: PR: New Feature

#58 Adding check for OSX during writing for bash shell
  .ci/install.sh
Labels: PR: Bugfix

#60 Disable colors for non-tty devices
  esy.lock/index.json
  package.json
Labels: PR: New Feature

#61 Fix a bug where `fnm env --multi` didn't used the default alias
  executable/Env.re
Labels: PR: Bugfix

#67 Use perl utils instead of custom written shasum
  .ci/shasum
  Dockerfile
Labels: PR: Internal

#57 Switch to cohttp(lwt) instead of curl
  Dockerfile
  README.md
  esy.lock/index.json
  esy.lock/opam/astring.0.8.3/opam
  esy.lock/opam/base-bytes.base/opam
  esy.lock/opam/base64.3.1.0/opam
  esy.lock/opam/cohttp-lwt-unix.2.0.0/opam
  esy.lock/opam/cohttp-lwt.2.0.0/opam
  esy.lock/opam/cohttp.2.0.0/opam
  esy.lock/opam/conduit-lwt-unix.1.4.0/opam
  esy.lock/opam/conduit-lwt.1.4.0/opam
  esy.lock/opam/conduit.1.4.0/opam
  esy.lock/opam/conf-openssl.1/files/osx-build.sh
  esy.lock/opam/conf-openssl.1/opam
  esy.lock/opam/conf-pkg-config.1.1/opam
  esy.lock/opam/fmt.0.8.5/opam
  esy.lock/opam/ipaddr.3.0.0/opam
  esy.lock/opam/jsonm.1.0.1/opam
  esy.lock/opam/logs.0.6.2/opam
  esy.lock/opam/lwt_ssl.1.1.2/opam
  esy.lock/opam/macaddr.3.0.0/opam
  esy.lock/opam/magic-mime.1.1.1/opam
  esy.lock/opam/ssl.0.5.7/opam
  esy.lock/opam/stringext.1.5.0/opam
  esy.lock/opam/uri.2.2.0/opam
  esy.lock/overrides/opam__s__conf_pkg_config_opam__c__1.1_opam_override/package.json
  esy.lock/overrides/opam__s__core__kernel_opam__c__v0.11.1_opam_override/package.json
  executable/dune
  library/Http.re
  library/Versions.re
  library/dune
  package.json
Labels: PR: New Feature

#64 Throw on errors in installation script
  .ci/install.sh
Labels: PR: Bugfix

#69 Fix version inference by throwing on http 404 again
  feature_tests/basic/run.sh
  feature_tests/existing_installation/run.sh
  feature_tests/matching-dotfiles/run.sh
  feature_tests/node-version/run.sh
  feature_tests/node_mirror_installation/run.sh
  feature_tests/nvmrc/run.sh
  feature_tests/partial_semver/run.sh
  library/Http.re
  library/Versions.re
Labels: PR: Bugfix

#70 Fix installation script parameters docs
  README.md
Labels: PR: Documentation
