Repository Schniz/fnm, pull requests merged in 2020-10, with the labels that each got.

#243 Add installation script testing
  .ci/install.sh
  .github/workflows/installation_script.yml
  .github/workflows/refmt.yml
Labels: PR: Internal

#244 Allow using homebrew to install with the installation script
  .ci/get_shell_profile.sh
  .ci/install.sh
  .ci/test_installation_script.sh
  .github/workflows/installation_script.yml
Labels: PR: New Feature

#245 Shorten the installation script
  .github/workflows/installation_script.yml
  README.md
  site/vercel.json
Labels: PR: Documentation

#247 fixed small error
  README.md
Labels: PR: Documentation

#248 Add `fnm --version` printing to CI
  .ci/get_shell_profile.sh
  .ci/install.sh
  .ci/test_installation_script.sh
  .github/workflows/installation_script.yml
Labels: PR: Not on Changelog

#268 Run CI on pull_request and push[master]
  .github/workflows/rust.yml
Labels: PR: Not on Changelog

#266 Use separate config file for fish config
  .ci/get_shell_profile.sh
  .ci/install.sh
  README.md
Labels: PR: Internal

#274 Add ARM support
  src/system_info.rs
Labels: PR: Internal

#275 Fix moving node install out of tmp directory
  Cargo.lock
  Cargo.toml
  src/directory_portal.rs
Labels: PR: Bugfix

#279 Remove UPX binary compression for now
  .github/workflows/rust.yml
Labels: PR: Internal

#281 docs: removed mentions of --multi from README
  README.md
Labels: PR: Documentation

#271 Update README for Windows instructions
  README.md
  docs/fnm.svg
  docs/recorded_screen_script.sh
  src/log_level.rs
Labels: PR: Documentation

#284 Fix npm not working because of wrong file copying
  Cargo.lock
  Cargo.toml
  src/directory_portal.rs
  src/downloader.rs
Labels: PR: Bugfix

#287 Remove `--multi` from install script
  .ci/install.sh
Labels: PR: Internal

#290 Fix shell inference in VSCode
  src/shell/infer/unix.rs
Labels: PR: Bugfix

#276 Add pre-built binaries for ARM32 and ARM64
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  src/system_info.rs
Labels: PR: New Feature

#293 Add detailed error instead of panic regarding `fnm env`
  src/commands/use.rs
Labels: PR: Documentation

#292 Add uninstall command
  src/alias.rs
  src/choose_version_for_user_input.rs
  src/cli.rs
  src/commands/install.rs
  src/commands/ls_local.rs
  src/commands/mod.rs
  src/commands/uninstall.rs
  src/commands/use.rs
  src/installed_versions.rs
  src/user_version.rs
  src/version.rs
  tests/feature_tests/mod.rs
  tests/feature_tests/uninstall.rs
  tests/snapshots/e2e__feature_tests__uninstall__Bash.snap
  tests/snapshots/e2e__feature_tests__uninstall__Fish.snap
  tests/snapshots/e2e__feature_tests__uninstall__PowerShell.snap
  tests/snapshots/e2e__feature_tests__uninstall__Zsh.snap
Labels: PR: New Feature

#295 Add a warning if MULTISHELL env var is not in PATH
  src/commands/use.rs
Labels: PR: Documentation

#297 Update CI badge
  README.md
Labels: PR: Documentation

#301 UserVersion: Fix different parsing for leading `v`
  src/user_version.rs
Labels: PR: Bugfix

#289 Remove logs from automatic version switching in `--use-on-cd`
  src/shell/bash.rs
  src/shell/fish.rs
  src/shell/zsh.rs
Labels: PR: Bugfix

#303 Add ARM handling to installation script
  .ci/install.sh
  .github/workflows/installation_script.yml
Labels: PR: Bugfix

#304 Make the first installed version the default one
  src/commands/install.rs
  src/config.rs
Labels: PR: New Feature

#306 Throw an error instead of panicking when can't infer shell
  src/commands/completions.rs
  src/commands/env.rs
  src/shell/mod.rs
Labels: PR: Documentation

#308 Allow unsuccessful symlink deletion in `fnm use`
  src/cli.rs
  src/commands/env.rs
  src/commands/install.rs
  src/commands/use.rs
  src/config.rs
Labels: PR: Bugfix

#310 Better error handling in symlink replacement
  src/commands/use.rs
Labels: PR: Bugfix

#307 Refer to homebrew/core formula instead of custom tap
  .ci/install.sh
  .github/workflows/installation_script.yml
  README.md
Labels: PR: Documentation
