Repository Schniz/fnm, pull requests merged in 2020-11, with the labels that each got.

#317 Bring back --using-file flag with a deprecation warning.
  src/commands/exec.rs
Labels: PR: Bugfix

#315 Add `list` alias for `ls`
  README.md
  src/cli.rs
Labels: PR: New Feature

#322 Run `fnm use` on shell initialization in Bash
  src/shell/bash.rs
  src/shell/fish.rs
  src/shell/zsh.rs
Labels: PR: Bugfix

#323 Escape `cd` calls in Bash's use-on-cd
  src/shell/bash.rs
Labels: PR: Bugfix

#326 Make config arguments globally available on all commands
  src/config.rs
Labels: PR: Bugfix

#327 Make ls and ls-remote aliases visible
  src/cli.rs
Labels: PR: Documentation

#334 Add installation instructions from cargo
  README.md
Labels: PR: Documentation

#329 Add scoop support
  README.md
Labels: PR: Documentation

#341 Update installation instructions
  README.md
Labels: PR: Documentation
