Repository Schniz/fnm, pull requests merged in 2020-03, with the labels that each got.

#199 Fix typo criterias -> criteria
  executable/ListRemote.re
  executable/Uninstall.re
Labels: PR: Bugfix

#201 Create alias from version range (fix #185)
  executable/Alias.re
Labels: PR: New Feature

#204 Improve eval expression in `README.md`
  README.md
Labels: PR: Documentation

#207 Format dotfiles versions before comparison
  .gitignore
  feature_tests/almost-matching-dotfiles/.node-version
  feature_tests/almost-matching-dotfiles/.nvmrc
  feature_tests/almost-matching-dotfiles/run.sh
  library/Dotfiles.re
Labels: PR: Bugfix
