Repository Schniz/fnm, pull requests merged in 2020-02, with the labels that each got.

#190 Add majorVersion option to ls-remote
  executable/FnmApp.re
  executable/ListRemote.re
  test/TestFnm.re
  test/TestListRemote.re
Labels: PR: New Feature

#191 uninstall allow prefix (fix #121)
  executable/Uninstall.re
  test/TestFnm.re
  test/TestUninstall.re
Labels: PR: New Feature

#197 Fix capitalization of message in Use.re
  executable/Use.re
Labels: PR: Bugfix

#202 Update rely
  esy.lock/index.json
  esy.lock/opam/dune-configurator.2.3.1/opam
  esy.lock/opam/dune-private-libs.2.3.1/opam
  esy.lock/opam/dune.2.3.1/opam
  esy.lock/opam/lwt.5.1.2/opam
  esy.lock/opam/ppx_deriving.4.4.1/opam
  esy.lock/opam/result.1.5/opam
  package.json
Labels: PR: Internal

#200 Do not repeat installation prompt for unrecognized versions
  executable/Use.re
Labels: PR: Bugfix
