Repository Schniz/fnm, pull requests merged in 2021-12, with the labels that each got.

#586 Revert the change to ureq
  Cargo.lock
  Cargo.toml
  src/archive/extract.rs
  src/archive/zip.rs
  src/commands/install.rs
  src/commands/ls_remote.rs
  src/downloader.rs
  src/http.rs
  src/main.rs
  src/remote_node_index.rs
Labels: PR: Bugfix

#605 Add a user-agent header
  src/http.rs
Labels: PR: Bugfix

#416 Respect $XDG_DATA_HOME
  src/config.rs
Labels: PR: New Feature

#606 Migrate to Rust 2021 edition
  Cargo.lock
  Cargo.toml
  src/archive/zip.rs
  src/commands/command.rs
  src/commands/env.rs
  src/commands/exec.rs
  src/commands/install.rs
  src/commands/uninstall.rs
  src/commands/use.rs
  src/config.rs
  src/directory_portal.rs
  src/downloader.rs
  src/log_level.rs
Labels: PR: Internal

#607 Allow recursive version lookups
  docs/commands.md
  src/commands/env.rs
  src/commands/exec.rs
  src/commands/install.rs
  src/commands/uninstall.rs
  src/commands/use.rs
  src/config.rs
  src/default_version.rs
  src/main.rs
  src/shell/bash.rs
  src/shell/fish.rs
  src/shell/powershell.rs
  src/shell/windows_cmd/cd.cmd
  src/shell/zsh.rs
  src/user_version_reader.rs
  src/version_file_strategy.rs
  src/version_files.rs
Labels: PR: New Feature

#603 (re)Include feature for (native) certificates
  Cargo.lock
  Cargo.toml
Labels: PR: Bugfix

#613 Don't warn on `~/.fnm` yet
  src/config.rs
Labels: PR: Bugfix
