Repository Schniz/fnm, pull requests merged in 2021-08, with the labels that each got.

#514 Invoke fnm use on startup for PowerShell
  src/shell/powershell.rs
Labels: PR: Bugfix

#512 fix(dep): Revert "Include feature for (native) certificates #468"
  Cargo.lock
  Cargo.toml
Labels: PR: Bugfix

#516 More informative log level error message
  src/log_level.rs
Labels: PR: Documentation

#519 Windows: Use junctions rather than symlinks
  Cargo.lock
  Cargo.toml
  README.md
  src/fs.rs
Labels: PR: New Feature

#496 install.sh: print an exit message for missing deps
  .ci/install.sh
Labels: PR: Documentation
