Repository Schniz/fnm, pull requests merged in 2021-03, with the labels that each got.

#401 Allow using filenames in --using=
  src/commands/exec.rs
  src/commands/install.rs
  src/commands/uninstall.rs
  src/commands/use.rs
  src/main.rs
  src/user_version_reader.rs
  src/version_files.rs
Labels: PR: New Feature

#403 Allow `fnm use` to use a file path
  src/commands/exec.rs
  src/commands/use.rs
Labels: PR: New Feature

#405 Fix a couple typos
  .ci/install.sh
  CHANGELOG.md
  README.md
Labels: PR: Documentation

#404 Ignore LogLevel on `fnm ls`
  src/commands/ls_local.rs
Labels: PR: Bugfix

#408 Fix ARM builds CI
  .github/workflows/rust.yml
Labels: PR: Internal

#411 Call the fnm use-on-cd hook on fish initialization
  src/shell/fish.rs
Labels: PR: Bugfix

#414 More meaningful error message when a subprocess is killed
  src/commands/exec.rs
Labels: PR: Bugfix

#413 Improve "version not found" error message
  src/commands/use.rs
Labels: PR: Bugfix
