Repository Schniz/fnm, pull requests merged in 2021-07, with the labels that each got.

#484 fix: --install-if-missing when using version alias
  src/commands/use.rs
  tests/feature_tests/mod.rs
  tests/feature_tests/snapshots/e2e__feature_tests__use_alias_install_if_missing__Bash.snap
  tests/feature_tests/snapshots/e2e__feature_tests__use_alias_install_if_missing__Fish.snap
  tests/feature_tests/snapshots/e2e__feature_tests__use_alias_install_if_missing__PowerShell.snap
  tests/feature_tests/snapshots/e2e__feature_tests__use_alias_install_if_missing__Zsh.snap
  tests/feature_tests/snapshots/e2e__feature_tests__use_alias_not_installed__Bash.snap
  tests/feature_tests/snapshots/e2e__feature_tests__use_alias_not_installed__Fish.snap
  tests/feature_tests/snapshots/e2e__feature_tests__use_alias_not_installed__PowerShell.snap
  tests/feature_tests/snapshots/e2e__feature_tests__use_alias_not_installed__Zsh.snap
Labels: PR: Bugfix

#493 Add instructions to setup the file for Cmder
  README.md
Labels: PR: Documentation

#489 Add unalias command
  docs/commands.md
  src/cli.rs
  src/commands/mod.rs
  src/commands/unalias.rs
  tests/feature_tests/mod.rs
  tests/feature_tests/snapshots/e2e__feature_tests__unalias__Bash.snap
  tests/feature_tests/snapshots/e2e__feature_tests__unalias__Fish.snap
  tests/feature_tests/snapshots/e2e__feature_tests__unalias__PowerShell.snap
  tests/feature_tests/snapshots/e2e__feature_tests__unalias__Zsh.snap
  tests/feature_tests/snapshots/e2e__feature_tests__unalias_error__Bash.snap
  tests/feature_tests/snapshots/e2e__feature_tests__unalias_error__Fish.snap
  tests/feature_tests/snapshots/e2e__feature_tests__unalias_error__PowerShell.snap
  tests/feature_tests/snapshots/e2e__feature_tests__unalias_error__Zsh.snap
Labels: PR: New Feature
