Repository Schniz/fnm, pull requests merged in 2022-11, with the labels that each got.

#850 [e2e] allow jest to run in parallel
  package.json
Labels: PR: Internal

#851 Add a debug workflow
  .github/workflows/debug.yml
Labels: PR: Internal

#800 Added json option to env command
  .changeset/chilly-apes-travel.md
  .github/workflows/rust.yml
  docs/commands.md
  e2e/__snapshots__/env.test.ts.snap
  e2e/env.test.ts
  e2e/shellcode/script.ts
  e2e/shellcode/shells/index.ts
  e2e/shellcode/shells/redirect-output.ts
  e2e/shellcode/shells/types.ts
  e2e/system-node.test.ts
  src/commands/env.rs
Labels: PR: New Feature, automerge

#852 migrate js scripts to esm
  .ci/prepare-version.js
  .ci/print-command-docs.js
  .github/workflows/debug.yml
  e2e/aliases.test.ts
  e2e/basic.test.ts
  e2e/current.test.ts
  e2e/describe.ts
  e2e/env.test.ts
  e2e/exec.test.ts
  e2e/existing-installation.test.ts
  e2e/latest-lts.test.ts
  e2e/log-level.test.ts
  e2e/multishell.test.ts
  e2e/nvmrc-lts.test.ts
  e2e/shellcode/script.ts
  e2e/shellcode/shells.ts
  e2e/shellcode/shells/cmdCall.ts
  e2e/shellcode/shells/cmdEnv.ts
  e2e/shellcode/shells/expect-command-output.ts
  e2e/shellcode/shells/output-contains.ts
  e2e/shellcode/shells/redirect-output.ts
  e2e/shellcode/shells/sub-shell.ts
  e2e/shellcode/test-bin-dir.ts
  e2e/shellcode/test-cwd.ts
  e2e/shellcode/test-node-version.ts
  e2e/system-node.test.ts
  e2e/uninstall.test.ts
  jest.config.cjs
  package.json
  pnpm-lock.yaml
  tsconfig.json
Labels: PR: Internal

#614 Make installation script respect $XDG_DATA_HOME
  .changeset/yellow-otters-develop.md
  .ci/install.sh
  .github/workflows/installation_script.yml
Labels: PR: Bugfix

#859 feat: support `fnm install --latest`
  .changeset/warm-rice-appear.md
  .ci/prepare-version.js
  .ci/print-command-docs.js
  docs/commands.md
  src/commands/install.rs
  src/user_version.rs
  src/version.rs
Labels: PR: New Feature, automerge

#864 fix "ensure commands are up to date" job
  .github/workflows/rust.yml
Labels: PR: Internal

#816 Replace semver with node-semver
  .changeset/serious-parents-tease.md
  Cargo.lock
  Cargo.toml
  src/current_version.rs
  src/installed_versions.rs
  src/user_version.rs
  src/user_version_reader.rs
  src/version.rs
Labels: PR: New Feature
