Repository Schniz/fnm, pull requests merged in 2022-07, with the labels that each got.

#759 add Rust Caching to CI
  .github/workflows/rust.yml
  renovate.json
Labels: PR: Internal, automerge

#760 Add Changesets to release fnm
  .changeset/README.md
  .changeset/clever-carrots-work.md
  .changeset/config.json
  .ci/generate-changelog.sh
  .ci/prepare-version.js
  .ci/record_screen.sh
  .ci/recorded_screen_script.sh
  .ci/type-letters.js
  .github/workflows/release.yml
  .gitignore
  package.json
  pnpm-lock.yaml
  yarn.lock
Labels: PR: Internal

#768 fix: Use correct PATH for npm install test
  .changeset/soft-laws-doubt.md
  src/downloader.rs
Labels: PR: Bugfix
