Repository Schniz/fnm, pull requests merged in 2022-01, with the labels that each got.

#616 Use on cd by default
  README.md
Labels: PR: Documentation

#598 Update README.md file emoji
  README.md
Labels: PR: Documentation

#626 Create the multishells directory if it is missing
  src/commands/use.rs
Labels: PR: Bugfix

#630 Replace `snafu` with `thiserror`
  Cargo.lock
  Cargo.toml
  src/choose_version_for_user_input.rs
  src/commands/alias.rs
  src/commands/completions.rs
  src/commands/env.rs
  src/commands/exec.rs
  src/commands/install.rs
  src/commands/ls_local.rs
  src/commands/ls_remote.rs
  src/commands/unalias.rs
  src/commands/uninstall.rs
  src/commands/use.rs
  src/current_version.rs
  src/downloader.rs
  src/installed_versions.rs
Labels: PR: Internal

#637 [Documentation] Adds Additional info regarding .node-version
  README.md
Labels: PR: Documentation

#638 Use local cache directory instead of temp directory for symlinks
  src/commands/env.rs
  src/directories.rs
  src/main.rs
Labels: PR: Bugfix, automerge

#625 Revert from using sysinfo, but only on Unix machines
  src/shell/infer/mod.rs
  src/shell/infer/unix.rs
  src/shell/infer/windows.rs
Labels: PR: Bugfix, automerge

#652 Fix `fnm completions`
  src/cli.rs
Labels: PR: Bugfix, automerge
