Repository Schniz/fnm, pull requests merged in 2023-06, with the labels that each got.

#960 allow to automatically enable corepack
  .changeset/dry-rocks-smash.md
  .changeset/rare-otters-perform.md
  docs/commands.md
  e2e/__snapshots__/corepack.test.ts.snap
  e2e/corepack.test.ts
  e2e/env.test.ts
  e2e/shellcode/script.ts
  e2e/shellcode/shells/cmdEnv.ts
  package.json
  pnpm-lock.yaml
  src/commands/env.rs
  src/commands/exec.rs
  src/commands/install.rs
  src/commands/use.rs
  src/config.rs
  src/shell/bash.rs
  src/shell/fish.rs
  src/shell/mod.rs
  src/shell/windows_compat.rs
  src/shell/zsh.rs
  src/version.rs
Labels: PR: New Feature

#977 fix workflow arguments
  .github/workflows/rust.yml
Labels: PR: Internal

#976 Add a test proxy server so we won't hit Node.js dist so much
  .gitignore
  e2e/shellcode/script.ts
  jest.config.cjs
  jest.global-setup.js
  jest.global-teardown.js
  tests/proxy-server/index.mjs
Labels: PR: Internal, automerge

#963 Capitalised "n" to reflect default option
  src/commands/use.rs
Labels: automerge
