Repository Schniz/fnm, pull requests merged in 2024-10, with the labels that each got.

#1184 fix: list-remote --filter --latest panics when filter has no results
  .changeset/plenty-flies-refuse.md
  src/commands/ls_remote.rs
Labels: hacktoberfest-accepted

#1195 fix: download failure when remote file is missing and add support for tar.gz archives
  .changeset/giant-falcons-cover.md
  Cargo.lock
  Cargo.toml
  e2e/__snapshots__/old-versions.test.ts.snap
  e2e/old-versions.test.ts
  src/archive/extract.rs
  src/archive/mod.rs
  src/archive/tar.rs
  src/archive/tar_xz.rs
  src/archive/zip.rs
  src/downloader.rs
  tests/proxy-server/index.mjs
Labels: hacktoberfest-accepted, automerge

#1277 Having alias for install and uninstall commands
  .changeset/gold-onions-lie.md
  docs/commands.md
  e2e/__snapshots__/uninstall.test.ts.snap
  e2e/uninstall.test.ts
  src/cli.rs
Labels: automerge
